### PR TITLE
:bug: Issues working behind Proxy

### LINKED ISSUE #214: Issues working behind Proxy
**Describe the bug**

Tried this utility behind proxy, try to set the proxy different ways none of them seems to be working. 
1.	Set the proxy outside of the utility -Djava.net.useSystemProxies=true, then it gives the below error
2.      Also tried to set the proxy at the Java Path.

java -Djava.net.useSystemProxies=true -Dhttps.proxyHost=***.**.com -Dhttps.proxyPort=**** -classpath okta-aw
s-cli-1.0.2.jar com.okta.tools.awscli
Sep 30, 2018 8:42:13 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://proxy.cna.com:8080->https
://cnapreview.okta.com:443: Malformed reply from SOCKS server
Sep 30, 2018 8:42:13 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cna.com:8080->https://cnapreview.okta.com:443
Sep 30, 2018 8:42:25 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://proxy.cna.com:8080->https
://cnapreview.okta.com:443: Malformed reply from SOCKS server
Sep 30, 2018 8:42:25 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cna.com:8080->https://cnapreview.okta.com:443
Sep 30, 2018 8:42:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://proxy.cna.com:8080->https
://cnapreview.okta.com:443: Malformed reply from SOCKS server
Sep 30, 2018 8:42:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cna.com:8080->https://cnapreview.okta.com:443
Exception in thread "main" java.net.SocketException: Malformed reply from SOCKS server
        at java.net.SocksSocketImpl.readSocksReply(Unknown Source)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by AlainODea**
Problem Statement
-----------------
Issue #214 states:
> Tried this utility behind proxy, try to set the proxy different ways none of them seems to be working.
> 
> 1. Set the proxy outside of the utility -Djava.net.useSystemProxies=true, then it gives the below error
> 
> 2. Also tried to set the proxy at the Java Path.
> 
> ```
> java -Djava.net.useSystemProxies=true -Dhttps.proxyHost=_**.**.com -Dhttps.proxyPort=_*** -classpath okta-aws-cli-1.0.2.jar com.okta.tools.awscli
> Sep 30, 2018 8:42:13 PM org.apache.http.impl.execchain.RetryExec execute
> INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->[http://proxy.cna.com:8080->https](http://proxy.cna.com:8080-%3Ehttps)
> ://cnapreview.okta.com:443: Malformed reply from SOCKS server
> Sep 30, 2018 8:42:13 PM org.apache.http.impl.execchain.RetryExec execute
> INFO: Retrying request to {tls}->[http://proxy.cna.com:8080->https://cnapreview.okta.com:443](http://proxy.cna.com:8080-%3Ehttps://cnapreview.okta.com:443)
> Sep 30, 2018 8:42:25 PM org.apache.http.impl.execchain.RetryExec execute
> INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->[http://proxy.cna.com:8080->https](http://proxy.cna.com:8080-%3Ehttps)
> ://cnapreview.okta.com:443: Malformed reply from SOCKS server
> Sep 30, 2018 8:42:25 PM org.apache.http.impl.execchain.RetryExec execute
> INFO: Retrying request to {tls}->[http://proxy.cna.com:8080->https://cnapreview.okta.com:443](http://proxy.cna.com:8080-%3Ehttps://cnapreview.okta.com:443)
> Sep 30, 2018 8:42:37 PM org.apache.http.impl.execchain.RetryExec execute
> INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->[http://proxy.cna.com:8080->https](http://proxy.cna.com:8080-%3Ehttps)
> ://cnapreview.okta.com:443: Malformed reply from SOCKS server
> Sep 30, 2018 8:42:37 PM org.apache.http.impl.execchain.RetryExec execute
> INFO: Retrying request to {tls}->[http://proxy.cna.com:8080->https://cnapreview.okta.com:443](http://proxy.cna.com:8080-%3Ehttps://cnapreview.okta.com:443)
> Exception in thread "main" java.net.SocketException: Malformed reply from SOCKS server
> at java.net.SocksSocketImpl.readSocksReply(Unknown Source)

Solution
--------
 - Add SOCKS proxy support

Resolves #214

### CODE REVIEW

**Comment by AlainODea** [comment]
@NaveenAtCNA this should fix your issue. I have tested this with a SOCKS proxy, an HTTP proxy, and no proxy and it works in all cases. Can you code review this?

File: src/main/java/com/okta/tools/helpers/HttpHelper.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+    public static CloseableHttpClient createClient(HttpClientBuilder httpClientBuilder)
+    {
+        Registry<ConnectionSocketFactory> reg = RegistryBuilder.<ConnectionSocketFactory>create()
+                .register("http", ProxySelectorPlainConnectionSocketFactory.INSTANCE)
+                .register("https", new ProxySelectorSSLConnectionSocketFactory(SSLContexts.createSystemDefault()))
+                .build();
+        PoolingHttpClientConnectionManager cm = new PoolingHttpClientConnectionManager(reg);
+        return httpClientBuilder
+                .useSystemProperties()
+                .setConnectionManager(cm)
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/HttpHelper.java]: **useSystemProperties()** is equivalent to the builder configuration used by **HttpClients.createSystem()**.
**setConnectionManager(cm)** allows us to dynamically create proxy sockets with SOCKS support when needed.

File: src/main/java/com/okta/tools/helpers/HttpHelper.java [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+        return createClient(HttpClients.custom());
+    }
+
+    private enum ProxySelectorPlainConnectionSocketFactory implements ConnectionSocketFactory {
+        INSTANCE;
+
+        @Override
+        public Socket createSocket(HttpContext context) throws IOException {
+            Socket socket = HttpHelper.createSocket(context);
+            return socket != null ? socket : PlainConnectionSocketFactory.INSTANCE.createSocket(context);
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/HttpHelper.java]: Attempt to create a compatible proxy socket adapter. Fall back to default plain connection implementation if a compatible proxy socket adapter cannot be created.

File: src/main/java/com/okta/tools/helpers/HttpHelper.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+        }
+
+        @Override
+        public Socket connectSocket(int connectTimeout, Socket sock, HttpHost host, InetSocketAddress remoteAddress, InetSocketAddress localAddress, HttpContext context) throws IOException {
+            return PlainConnectionSocketFactory.INSTANCE.connectSocket(connectTimeout, sock, host, remoteAddress, localAddress, context);
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/HttpHelper.java]: Use default plain connection implementation for connecting.

File: src/main/java/com/okta/tools/helpers/HttpHelper.java [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+
+    private static final class ProxySelectorSSLConnectionSocketFactory extends SSLConnectionSocketFactory {
+        ProxySelectorSSLConnectionSocketFactory(SSLContext sslContext) {
+            super(sslContext);
+        }
+
+        @Override
+        public Socket createSocket(HttpContext context) throws IOException {
+            Socket socket = HttpHelper.createSocket(context);
+            return socket != null ? socket : super.createSocket(context);
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/HttpHelper.java]: Attempt to create a compatible proxy socket adapter. Fall back to default TLS connection implementation if a compatible proxy socket adapter cannot be created.

File: src/main/java/com/okta/tools/helpers/HttpHelper.java [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+        }
+    }
+
+    private static Socket createSocket(HttpContext context) {
+        HttpHost httpTargetHost = (HttpHost) context.getAttribute(HttpCoreContext.HTTP_TARGET_HOST);
+        URI uri = URI.create(httpTargetHost.toURI());
+        Proxy proxy = ProxySelector.getDefault().select(uri).iterator().next();
+        return proxy.type().equals(Proxy.Type.SOCKS) ? new Socket(proxy) : null;
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/HttpHelper.java]: Create a SOCKS socket if there is a SOCKS proxy. Default to null. Java's Socket type supports HTTP proxies, but Apache HTTP Client is not compatible with it.
