### PR TITLE
:bug: Profile names break AWS Java SDK 2

### LINKED ISSUE #208: profile names in ~/.aws/config and ~/.aws/credentials file are not compatible with AWS Java SDK V2
please see discussion here: https://github.com/aws/aws-sdk-java-v2/issues/389#issuecomment-421195380

### PR DESCRIPTION
**Pull request by AlainODea**
Problem Statement
-----------------
Issue #208 states:
> please see discussion here: [aws/aws-sdk-java-v2#389 (comment)](https://github.com/aws/aws-sdk-java-v2/issues/389#issuecomment-421195380)

Solution
--------
 - Use roleName_account as generated role name (fallback to "temp")

Resolves #208

### CODE REVIEW

**Comment by AlainODea** [comment]
@jpollard-cs can you code review this for me, please? I think it fixes your issue.

File: src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java [hunk 1]
```diff
@@ -125,7 +125,7 @@ private ProfileSAMLResult doRequest(Instant startInstant) throws IOException {
         Instant sessionExpiry = startInstant.plus(assumeRequest.getDurationSeconds() - 30, ChronoUnit.SECONDS);
         AssumeRoleWithSAMLResult assumeResult = roleHelper.assumeChosenAwsRole(assumeRequest);
 
-        String profileName = profileHelper.getProfileName(assumeResult, environment.oktaProfile);
+        String profileName = profileHelper.getProfileName(assumeResult);
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java]: :art: the environment is already in scope of the call, so there's no need to hand it in.

File: src/main/java/com/okta/tools/helpers/ProfileHelper.java [hunk 2]
```diff
@@ -6,11 +6,15 @@
...
 import java.io.IOException;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
 
 public class ProfileHelper {
 
     private final CredentialsHelper credentialsHelper;
     private OktaAwsCliEnvironment environment;
+    private final Pattern assumedRoleUserPattern = Pattern.compile(
+            "^arn:aws:sts::(?<account>\\d{12}):assumed-role/(?<roleName>[^/]*)/(?<userName>.*$)");
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/ProfileHelper.java]: 🌱 "parser" for the assumed role ARN. Allows us to get the account number, role name, and user name from the ARN to build a cleaner profile name.

File: src/main/java/com/okta/tools/helpers/ProfileHelper.java [hunk 3]
```diff
@@ -31,17 +35,17 @@ public void createAwsProfile(AssumeRoleWithSAMLResult assumeResult, String crede
...
-            if (credentialsProfileName.startsWith("arn:aws:sts::")) {
-                credentialsProfileName = credentialsProfileName.substring(13);
-            }
-            if (credentialsProfileName.contains(":assumed-role")) {
-                credentialsProfileName = credentialsProfileName.replaceAll(":assumed-role", "");
+            Matcher matcher = assumedRoleUserPattern.matcher(credentialsProfileName);
+            if (matcher.matches()) {
+                credentialsProfileName = matcher.group("roleName") + "_" + matcher.group("account");
+            } else {
+                credentialsProfileName = "temp";
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/ProfileHelper.java]: :seedling: use the "parser" to pull our the role name and account number and use them to build the role name.

Having the account alias would be nice, but it's a bit clumsy to thread that from the role selection menu to here. Baby steps to fix the bug then polish later.

File: src/main/java/com/okta/tools/helpers/ProfileHelper.java [hunk 4]
```diff
@@ -31,17 +35,17 @@ public void createAwsProfile(AssumeRoleWithSAMLResult assumeResult, String crede
         credentialsHelper.updateCredentialsFile(credentialsProfileName, awsAccessKey, awsSecretKey, awsSessionToken);
     }
 
-    public String getProfileName(AssumeRoleWithSAMLResult assumeResult, String oktaProfile) {
+    public String getProfileName(AssumeRoleWithSAMLResult assumeResult) {
         String credentialsProfileName;
-        if (StringUtils.isNotBlank(oktaProfile)) {
-            credentialsProfileName = oktaProfile;
+        if (StringUtils.isNotBlank(environment.oktaProfile)) {
+            credentialsProfileName = environment.oktaProfile;
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/ProfileHelper.java]: :art: just use the environment. We already have it in scope.
