### PR TITLE
:bug: Correctly handle nested configs

### LINKED ISSUE #141: Configurations with nested configs improperly handeled
Existing `~/.aws/config` with nested properties are overwritten improperly by this tool.
For example, `s3` configuration uses [indentation for its properties](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html) e.g.
```
[profile development]
aws_access_key_id=foo
aws_secret_access_key=bar
s3 =
  max_concurrent_requests = 20
  max_queue_size = 10000
```
When `awscli` is run, the `config` is written out like so:
```
[profile development]
aws_access_key_id=foo
aws_secret_access_key=bar
s3 =
max_concurrent_requests = 20
max_queue_size = 10000
```
which is not correctly read by `aws s3` commands!

Specifically, the following test https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/054c45c5b0b58195db45bd25b528c0436331d7ed/src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java#L110-L130 if modified to contain s3 keys as follows:
```java
    @Test
    void addOrUpdateProfileToExistingProfile() throws IOException {
        final String existingCombined = manualRole + "\n"
                + "s3 =\n"
                + "    max_queue_size = 1000" + "\n\n" + existingProfile;

        final StringReader configurationReader = new StringReader(existingCombined);
        final StringWriter configurationWriter = new StringWriter();
        final Configuration configuration = new Configuration(configurationReader);

        final String updatedPrefix = "updated_";
        final String expected = "[profile " + profileName + "]\n"
                + Configuration.ROLE_ARN + " = " + updatedPrefix + role_arn + "\n"
                + SOURCE_PROFILE + " = " + profileName + "_source\n"
                + Configuration.REGION + " = " + region + "\n"
                + "s3 =\n"
                + "    max_queue_size = 1000"
                + "\n\n" + existingProfile;


        configuration.addOrUpdateProfile(profileName, updatedPrefix + role_arn);
        configuration.save(configurationWriter);

        String given = StringUtils.remove(configurationWriter.toString().trim(), '\r');

        assertEquals(expected, given);
    }
```
will not pass.

### PR DESCRIPTION
**Pull request by AlainODea**
Problem Statement
-----------------

Issue #141 states:
> Existing `~/.aws/config` with nested properties are overwritten improperly by this tool.
> For example, `s3` configuration uses [indentation for its properties](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html) e.g.
> ```
> [profile development]
> aws_access_key_id=foo
> aws_secret_access_key=bar
> s3 =
>   max_concurrent_requests = 20
>   max_queue_size = 10000
> ```
> When `awscli` is run, the `config` is written out like so:
> ```
> [profile development]
> aws_access_key_id=foo
> aws_secret_access_key=bar
> s3 =
> max_concurrent_requests = 20
> max_queue_size = 10000
> ```
> which is not correctly read by `aws s3` commands!
> 
> Specifically, the following test https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/054c45c5b0b58195db45bd25b528c0436331d7ed/src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java#L110-L130 if modified to contain s3 keys as follows:
> ```java
>     @Test
>     void addOrUpdateProfileToExistingProfile() throws IOException {
>         final String existingCombined = manualRole + "\n"
>                 + "s3 =\n"
>                 + "    max_queue_size = 1000" + "\n\n" + existingProfile;
> 
>         final StringReader configurationReader = new StringReader(existingCombined);
>         final StringWriter configurationWriter = new StringWriter();
>         final Configuration configuration = new Configuration(configurationReader);
> 
>         final String updatedPrefix = "updated_";
>         final String expected = "[profile " + profileName + "]\n"
>                 + Configuration.ROLE_ARN + " = " + updatedPrefix + role_arn + "\n"
>                 + SOURCE_PROFILE + " = " + profileName + "_source\n"
>                 + Configuration.REGION + " = " + region + "\n"
>                 + "s3 =\n"
>                 + "    max_queue_size = 1000"
>                 + "\n\n" + existingProfile;
> 
> 
>         configuration.addOrUpdateProfile(profileName, updatedPrefix + role_arn);
>         configuration.save(configurationWriter);
> 
>         String given = StringUtils.remove(configurationWriter.toString().trim(), '\r');
> 
>         assertEquals(expected, given);
>     }
> ```
> will not pass.

Solution
--------
 - Add Apache Commons Configuration2

 - Adapt configuration2's INIConfiguration to support AWS quirks

 - Remove Ini4j (unmaintained, has park page for website)

 - Refactor file handling code

Resolves #141

Apologies for the extensiveness of this change. The configuration
handling likely needs a refactor to make it easier to support future
modification.

### CODE REVIEW

File: src/main/java/com/okta/tools/aws/settings/Settings.java [hunk 1]
```diff
@@ -15,22 +15,26 @@
...
+import java.util.Set;
+import java.util.stream.Collectors;
 
 /**
  * A simple abstract class used to load AWS CLI settings files like the `credentials` or `config` files.
  */
 public abstract class Settings {
 
-    final Ini settings = new Ini();
+    private final AwsINIConfiguration settings;
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/aws/settings/Settings.java]: A huge chunk of the change stems from hiding this as exposing it causing Ini4j's API to leak into everywhere and my original attempt at this had Apache Commons Configuration2's API leaked into everywhere.

File: src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java [hunk 2]
```diff
@@ -0,0 +1,875 @@
+/*
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java]: 🤔 before calling me on this. I admit that this is a copy/paste from Apache Commons Configuration2. I tried to extend their class and it wasn't open to extension in this manner. I will look into contributing an extension point to their project so that we can later replace this with something much cleaner.

Comment (AlainODea) [reply src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java]: It's literally this code:
https://github.com/apache/commons-configuration/blob/trunk/src/main/java/org/apache/commons/configuration2/INIConfiguration.java

With some changes I'll highlight in the review.

File: src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java [hunk 3]
```diff
@@ -0,0 +1,875 @@
...
+ * limitations under the License.
+ */
+package com.okta.tools.aws.settings;
+
+import org.apache.commons.configuration2.*;
+import org.apache.commons.configuration2.convert.ListDelimiterHandler;
+import org.apache.commons.configuration2.ex.ConfigurationException;
+import org.apache.commons.configuration2.ex.ConfigurationRuntimeException;
+import org.apache.commons.configuration2.tree.*;
+import org.apache.commons.lang3.StringUtils;
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java]: ➕ added this so I could effectively right trim.

File: src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java [hunk 4]
```diff
@@ -0,0 +1,875 @@
...
+    private void createNodeBuilders(BufferedReader in,
+                                    ImmutableNode.Builder rootBuilder,
+                                    Map<String, ImmutableNode.Builder> sectionBuilders)
+            throws IOException
+    {
+        ImmutableNode.Builder sectionBuilder = rootBuilder;
+        String line = in.readLine();
+        while (line != null)
+        {
+            line = StringUtils.stripEnd(line, null);
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java]: ➕ right trim instead of trim the entire line:
https://github.com/apache/commons-configuration/blob/trunk/src/main/java/org/apache/commons/configuration2/INIConfiguration.java#L433

File: src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java [hunk 5]
```diff
@@ -0,0 +1,875 @@
...
+                    if (index >= 0)
+                    {
+                        key = line.substring(0, index);
+                        value = parseValue(line.substring(index + 1), in);
+                    }
+                    else
+                    {
+                        key = line;
+                    }
+                    key = StringUtils.stripEnd(key, null);
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java]: ➕ right trim instead of trim the key:
https://github.com/apache/commons-configuration/blob/trunk/src/main/java/org/apache/commons/configuration2/INIConfiguration.java#L461

File: src/test/java/com/okta/tools/aws/settings/CredentialsTest.java [hunk 6]
```diff
@@ -203,18 +194,4 @@ void addOrUpdateDefaultProfileToExistingProfile() throws IOException {
...
-    @Test
-    public void constructorClosesReader() throws Exception {
-        final String simpleIniDocument = "[ini]\nfoo=bar";
-        final StringReader reader = new StringReader(simpleIniDocument);
-
-        // This should consume reader
-        new Credentials(reader);
-        // Causing this to throw an exception
-        assertThrows(IOException.class, () -> reader.ready(), "Stream closed");
-    }
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/CredentialsTest.java]: This was an annoying behavior of Ini4j. Thankfully it is not preserved in configuration2.

File: src/test/java/com/okta/tools/aws/settings/CredentialsTest.java [hunk 7]
```diff
@@ -50,14 +49,6 @@
...
                     null, "_custom");
 
-    /*
-     * Test instantiating a Credentials object with invalid INI.
-     */
-    @Test
-    void instantiateInvalidCredentials() {
-        assertThrows(IOException.class, () -> new Credentials(new StringReader("someinvalidini")));
-    }
-
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/CredentialsTest.java]: This is technically a valid INI file. I couldn't figure out how to construct an invalid INI file. Ini4j got this wrong.

File: src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java [hunk 8]
```diff
@@ -238,46 +243,4 @@ void addOrUpdateProfileToExistingProfile() throws IOException {
...
-    @Test
-    public void constructorClosesReader() throws Exception {
-        final String simpleIniDocument = "[ini]\nfoo=bar";
-        final StringReader reader = new StringReader(simpleIniDocument);
-
-        // This should consume reader
-        new Configuration(reader);
-        // Causing this to throw an exception
-        assertThrows(IOException.class, () -> reader.ready(), "Stream closed");
-    }
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java]: This was an annoying behavior of Ini4j. Thankfully it is not preserved in configuration2.

File: src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java [hunk 9]
```diff
@@ -136,28 +146,23 @@ void addOrUpdateProfileToNewConfigFileWithCustomPrefix() throws IOException {
     void addOrUpdateDefaultProfileToNewConfigFile() throws IOException {
         Configuration initiallyEmpty = new Configuration(new StringReader(""));
 
-        // Small function to copy a section to a map so we can easily compare it
-        Function<Profile.Section, Map<String, String>> sectionToMap = section ->
-                section.entrySet().stream()
-                        .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
-
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java]: :art: moved this into Settings as it is generally useful and I wanted to hide the settings field to hide configuration2 from the rest of the client code.

File: src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java [hunk 10]
```diff
@@ -105,28 +89,54 @@ void addOrUpdateProfileToNewConfigFile() throws IOException {
...
+                + "    max_queue_size = 1000"
+                + "\n\n" + existingProfile;
+
+
+        configuration.addOrUpdateProfile(profileName, updatedPrefix + role_arn, region);
+        configuration.save(configurationWriter);
+
+        String given = StringUtils.remove(configurationWriter.toString().trim(), '\r');
+
+        assertEquals(expected, given);
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java]: ✅ worth adding a test to cover this nested config stuff seeing as it's what we came here to build.

File: src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java [hunk 11]
```diff
@@ -59,43 +56,30 @@
...
                     0, null, "custom ", null);
 
-    /*
-     * Test instantiating a Credentials object with invalid INI.
-     */
-    @Test
-    void instantiateInvalidConfiguration() {
-        assertThrows(IOException.class, () -> new Configuration(new StringReader("someinvalidini")));
-    }
-
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java]: This is technically a valid INI file. I couldn't figure out how to construct an invalid INI file. Ini4j got this wrong.

File: src/main/java/com/okta/tools/helpers/SessionHelper.java [hunk 12]
```diff
@@ -81,35 +88,20 @@ public void updateCurrentSession(Instant expiryInstant, String profileName) thro
...
-
-    private Path getMultipleProfilesPath() throws IOException {
-        return FileHelper.getFilePath(FileHelper.getOktaDirectory(), "profiles");
-    }
-
-    private MultipleProfile getMultipleProfile() throws IOException {
-        Reader reader = FileHelper.getReader(FileHelper.getOktaDirectory(), "profiles");
-
-        return new MultipleProfile(reader);
-    }
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/SessionHelper.java]: :art: I reordered the methods here to be in step-down order (Clean Code). Sorry for the diff carnage.

File: src/main/java/com/okta/tools/helpers/SessionHelper.java [hunk 13]
```diff
@@ -81,35 +88,20 @@ public void updateCurrentSession(Instant expiryInstant, String profileName) thro
...
-        MultipleProfile multipleProfile = getMultipleProfile();
-        multipleProfile.addOrUpdateProfile(environment.oktaProfile, environment.awsRoleToAssume, start);
-
-        try (final FileWriter fileWriter = FileHelper.getWriter(FileHelper.getOktaDirectory(), "profiles")) {
-            multipleProfile.save(fileWriter);
-        }
+        FileHelper.usingPath(FileHelper.getOktaDirectory().resolve("profiles"), (reader, writer) -> {
+            MultipleProfile multipleProfile = new MultipleProfile(reader);
+            multipleProfile.addOrUpdateProfile(environment.oktaProfile, environment.awsRoleToAssume, start);
+            multipleProfile.save(writer);
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/SessionHelper.java]: :art: I replaced the explicit resource management with a utility method that structurally ensures correct use without burdening every site of use.

File: src/main/java/com/okta/tools/helpers/SessionHelper.java [hunk 14]
```diff
@@ -26,43 +26,41 @@ public SessionHelper(OktaAwsCliEnvironment environment, CookieHelper cookieHelpe
...
-    /**
-     * Gets the current session file's path
-     *
-     * @return A {@link Path} for the current session file
-     * @throws IOException
-     */
-    private Path getSessionPath() throws IOException {
-        return FileHelper.resolveFilePath(FileHelper.getOktaDirectory(), ".current-session");
-    }
-
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/SessionHelper.java]: :art: a good chunk of the diff in this file is method reordering to show methods in the order they are used (step down rule from Clean Code).

File: src/main/java/com/okta/tools/helpers/FileHelper.java [hunk 15]
```diff
@@ -111,15 +110,34 @@ public static Path getFilePath(Path directoryPath, String fileName) throws IOExc
...
+    }
+
+    static void writingPath(Path path, PathW pathW) throws IOException {
+        try (Writer writer = getWriter(path)) {
+            pathW.useFile(writer);
+        }
+    }
+
+    public interface PathW {
+        void useFile(Writer writer) throws IOException;
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/FileHelper.java]: ❓ I'm not sure I love the names of these utility methods or interfaces, but I couldn't come up with anything better. I like the outcome in code tho.

File: src/main/java/com/okta/tools/aws/settings/Credentials.java [hunk 16]
```diff
@@ -60,21 +59,8 @@ public Credentials(Reader reader) throws IOException {
      */
     public void addOrUpdateProfile(String name, String awsAccessKey, String awsSecretKey, String awsSessionToken) {
         name = "default".equals(name) ? "default" : name + environment.credentialsSuffix;
```
Comment (frosforever) [inline src/main/java/com/okta/tools/aws/settings/Credentials.java]: Should this also be using `DEFAULT_PROFILE_NAME` instead?

Comment (AlainODea) [reply src/main/java/com/okta/tools/aws/settings/Credentials.java]: Definitely. I’ll fix that. Good catch.

**Comment by AlainODea** [comment]
@frosforever thank you for the code review. Any other concerns before I merge this?

File: src/main/java/com/okta/tools/aws/settings/MultipleProfile.java [hunk 17]
```diff
@@ -15,81 +15,61 @@
...
+        clearSection(profile);
     }
 
-    private Instant getExpiry(String oktaprofile, Ini ini) {
-        Ini.Section profilesection = ini.get(oktaprofile);
-        String profileExpiry = profilesection.get("profile_expiry");
-        Instant expiry = Instant.parse(profileExpiry);
-        return expiry;
+    private Instant getExpiry(String profile) {
+        String profileExpiry = getProperty(profile, "profile_expiry");
```
Comment (frosforever) [inline src/main/java/com/okta/tools/aws/settings/MultipleProfile.java]: Should this use static `PROFILE_EXPIRY`

File: src/main/java/com/okta/tools/aws/settings/MultipleProfile.java [hunk 18]
```diff
@@ -15,81 +15,61 @@
...
-     * Create a Profiles object from a given {@link Reader}. The data given by this {@link Reader} should
-     * be INI-formatted.
-     *
-     * @param reader The settings we want to work with. N.B.: The reader is consumed by the constructor.
-     * @throws IOException Thrown when we cannot read or load from the given {@param reader}.
-     */
-    public MultipleProfile(Reader reader) throws IOException {
-        super(reader);
+    private String getRoleArn(String profile) {
+        return getProperty(profile, "okta_roleArn");
```
Comment (frosforever) [inline src/main/java/com/okta/tools/aws/settings/MultipleProfile.java]: should this use static `OKTA_ROLE_ARN`

Comment (AlainODea) [reply src/main/java/com/okta/tools/aws/settings/MultipleProfile.java]: Thanks again. I've fixed these.
