### PR TITLE
:bug: Fix #113

### LINKED ISSUE #113: aws cli reassign the tocken
Hello,
I am able to setup 'okta-aws-cli-assume-role' tool successfully. 
Ran  'awscli sts get-caller-identity' command followed by aws cli commands (ex: aws s3 ls) with the  --profile <profile created by the tool>
Once the token expired after 1hr,  get this error when I ran aws s3 ls --profile <profile name>.
_An error occurred (ExpiredToken) when calling the ListBuckets operation: The provided token has expired_
So, ran command 'awscli sts get-caller-identity'. but getting the following error. 
Exception in thread "main" java.lang.IllegalStateException: Duplicate key DI07VqOgutdRFOEJZ0eHdgEEg
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.okta.tools.saml.OktaSaml.launchOktaAwsApp(OktaSaml.java:97)
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsRefresh(OktaSaml.java:60)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:46)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
	at com.okta.tools.awscli.main(awscli.java:33)

Is there anything missing with the configuration or the commands?

### PR DESCRIPTION
**Pull request by AlainODea**
Problem Statement
-----------------
Attempts to reassign AWS token fail due to duplicate named HTTP cookies.

Solution
--------
 - Filter cookies to Okta org domain when calling Okta APIs

 - Refactor to include Okta environment in CookieHelper

### CODE REVIEW

File: src/main/java/com/okta/tools/helpers/CookieHelper.java [hunk 1]
```diff
@@ -61,14 +67,16 @@ public static CookieStore loadCookies(OktaAwsCliEnvironment environment) throws
         return cookieStore;
     }
 
-    public static void storeCookies(CookieStore cookieStore) throws IOException {
+    public void storeCookies(CookieStore cookieStore) throws IOException {
         Properties properties = new Properties();
-        cookieStore.getCookies().stream().collect(Collectors.toMap(Cookie::getName, Cookie::getValue))
+        cookieStore.getCookies().stream()
+                .filter(c -> environment.oktaOrg.equals(c.getDomain()))
+                .collect(Collectors.toMap(Cookie::getName, Cookie::getValue, (x, y) -> y))
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/CookieHelper.java]: This is the salient part of this change. Everything else is refactoring junk.
