### PR TITLE
:bug: ~/.aws/config should not be written

### LINKED ISSUE #137: Extending CLI session duration & Okta+awscli setup documentation
Hello, I recently had an Okta support case (# 00465201) open for this, but after a little back and forth the case owner advised that I instead open a Github issue ticket for the dev team to address.

My initial inquiry is about extending the duration of CLI sessions.  I know there have been other questions about this, but earlier this year AWS introduced the ability to extend the CLI session for federated logins up to 12 hours (from the default of 1).  Per the case and as a test, I tried adding the OKTA_STS_SESSION parameter to my config.properties file (as described here https://github.com/oktadeveloper/okta-aws-cli-assume-role#configuring-the-application), but my federated CLI sessions continue to timeout after 1 hour.

I then got to thinking that perhaps my version of the okta-cli tool is out of date, as I originally setup our Okta+AWS integration back in 2016.   I noticed there is a new(er) version of the okta-aws-cli jar file (https://github.com/oktadeveloper/okta-aws-cli-assume-role/releases), so then thought mabye I needed to download that and/or the entire repo and start from scratch. Unfortunately, downloading just the new jar file (okta-aws-cli-1.0.2.jar) or the entire repo is not helping. I keep running into "request has expired" errors or java issues.

Additionally, the instructions on both the Github code page and the Okta support page (https://support.okta.com/help/Documentation/Knowledge_Article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta) appear to not be correct/entirely up-to-date. In some spots they are a little vague, they seem to be missing steps for use on Windows machines, and not fully updated. For example, the latest jar file to download is named okta-aws-cli-1.0.2.jar, but everywhere in the setup/installation steps the instructions talk about the old file name (oktaawscli.jar). The instructions do not say if we are supposed to rename the file, etc. The Github instructions also mention a lib folder, as well as needing the AWS Java SDK, but the current repo does not contain a lib folder. The old installation (aka what I've been using for almost 2 years) does. 

If I download the entire repo and try to start from scratch, I am not completely sure which files in the repo are absolutely needed and which I can perhaps dispose of. When I originally setup the AWS-Okta-cli integration 2 years ago, I was advised I only needed a lib and out directory and the files therein.

Thank you.

Tom

### LINKED ISSUE #199: aws sts caller identity issue
**Describe the bug**
Execute below after executing the okta cli code that generates the temp keys
aws sts get-caller-identity (this executes aws cli code) and retursn below
"Arn": "arn:aws:sts::123123123:assumed-role/role-name/botocore-session-123123123"

The generated session "botocore-session-123123123" does not work with policy userId or saml iam policy variables
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html

A possible solution is "role_session_name" from saml assertion in config file but this does not work entirely. The real session identifier is the "Federated Login: role/userId" in AWS web console.

Setting AWS_ACCESS_KEY_ID and other environment variables from okta cli saml response manually and executing "aws sts get-caller-identity" and tests with AWS IAM policy variables does work.
It does NOT work with using profile in ~/.aws/config and ~/.aws/credentials

I am trying to find the root cause and solution.

Can someone help clarify why docs state to call "sts get-caller-identity" like below and is this doing something with the aws session identifier?

Usage
aws test sts get-caller-identity

### PR DESCRIPTION
**Pull request by AlainODea**
Problem Statement
-----------------
Issue #199 states:
> **Describe the bug**
> Execute below after executing the okta cli code that generates the temp keys
> aws sts get-caller-identity (this executes aws cli code) and retursn below
> "Arn": "arn:aws:sts::123123123:assumed-role/role-name/botocore-session-123123123"
> 
> The generated session "botocore-session-123123123" does not work with policy userId or saml iam policy variables
> https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html
> 
> A possible solution is "role_session_name" from saml assertion in config file but this does not work entirely. The real session identifier is the "Federated Login: role/userId" in AWS web console.
> 
> Setting AWS_ACCESS_KEY_ID and other environment variables from okta cli saml response manually and executing "aws sts get-caller-identity" and tests with AWS IAM policy variables does work.
> It does NOT work with using profile in ~/.aws/config and ~/.aws/credentials
> 
> I am trying to find the root cause and solution.
> 
> Can someone help clarify why docs state to call "sts get-caller-identity" like below and is this doing something with the aws session identifier?
> 
> Usage
> aws test sts get-caller-identity

Solution
--------
 - Don't write ~/.aws/config

 - Remove requirement for self-AssumeRole on IAM role policy

 - Remove requirement for _source in credentials profiles

 - Remove OKTA_PROFILE_PREFIX

 - Remove OKTA_CREDENTIALS_SUFFIX

 - Bonus: actually reuse named sessions rather than hammering STS

Resolves #199 
Resolves #137

### CODE REVIEW

**Comment by AlainODea** [comment]
@jeugene I think this fixes your issue. Could you code review this?

**Comment by AlainODea** [comment]
@davidsuehring I think this fixes your issue. Could you code review this?

File: src/main/java/com/okta/tools/helpers/SessionHelper.java [hunk 1]
```diff
@@ -93,15 +94,15 @@ public void updateCurrentSession(Instant expiryInstant, String profileName) thro
...
         FileHelper.usingPath(FileHelper.getOktaDirectory().resolve("profiles"), reader -> {
             MultipleProfile multipleProfile = new MultipleProfile(reader);
-            multipleProfile.addOrUpdateProfile(environment.oktaProfile, environment.awsRoleToAssume, start);
+            multipleProfile.addOrUpdateProfile(environment.oktaProfile, environment.awsRoleToAssume, sessionExpiry);
             return multipleProfile;
         }, MultipleProfile::save);
     }
 
     public boolean sessionIsActive(Instant startInstant, Session session) {
-        return startInstant.isBefore(session.expiry);
```
Comment (AlainODea) [inline src/main/java/com/okta/tools/helpers/SessionHelper.java]: :bug: named profile sessions would result in sts:AssumeRoleWithSAMLResponse every time they were used since this logic didn't account for them.

File: src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java [hunk 2]
```diff
@@ -1,246 +0,0 @@
...
-
-
-        configuration.addOrUpdateProfile(profileName, updatedPrefix + role_arn, region);
-        configuration.save(configurationWriter);
-
-        String given = StringUtils.remove(configurationWriter.toString().trim(), '\r');
-
-        assertEquals(expected, given);
-    }
-}
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java]: :fire: tests for writing ~/.aws/config which we no longer write, so we no longer needed to test.

File: src/test/java/com/okta/tools/aws/settings/CredentialsTest.java [hunk 3]
```diff
@@ -35,19 +34,10 @@
     private String accessKey = "accesskey";
     private String secretKey = "secretkey";
     private String sessionToken = "sessiontoken";
-    private String manualRole = "[" + roleName + "_source]\n"
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/CredentialsTest.java]: :fire: the "_source" suffix was a workaround for improperly writing ~/.aws/config so it is no longer the default.

File: src/test/java/com/okta/tools/aws/settings/CredentialsTest.java [hunk 4]
```diff
@@ -35,19 +34,10 @@
...
             + Credentials.SESSION_TOKEN + " = " + sessionToken;
-    private String manualRoleCustomSuffix = "[" + roleName + "_custom]\n"
-            + Credentials.ACCES_KEY_ID + " = " + accessKey + "\n"
-            + Credentials.SECRET_ACCESS_KEY + " = " + secretKey + "\n"
-            + Credentials.SESSION_TOKEN + " = " + sessionToken;
-    private OktaAwsCliEnvironment environmentWithCustomSuffix =
-            new OktaAwsCliEnvironment(false, null, null,
-                    null, null, null, null,
-                    null, 0, null,
-                    null, false, "_custom");
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/CredentialsTest.java]: :fire: suffix customization was a workaround for the workaround causing problems for people using this with downstream tools. Removing the writes to ~/.aws/config makes suffix customization unnecessary.

File: src/test/java/com/okta/tools/aws/settings/CredentialsTest.java [hunk 5]
```diff
@@ -66,23 +56,6 @@ void addOrUpdateProfileToNewCredentialsFile() throws IOException {
...
-        final Credentials credentials = new Credentials(credentialsReader, environmentWithCustomSuffix);
-
-        credentials.addOrUpdateProfile(roleName, accessKey, secretKey, sessionToken);
-        credentials.save(credentialsWriter);
-
-        String given = org.apache.commons.lang.StringUtils.remove(credentialsWriter.toString().trim(), '\r');
-
-        assertEquals(manualRoleCustomSuffix, given);
-    }
-
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/CredentialsTest.java]: :fire: suffix customization was a workaround for the workaround causing problems for people using this with downstream tools. Removing the writes to ~/.aws/config makes testing suffix customization unnecessary.

File: src/test/java/com/okta/tools/aws/settings/CredentialsTest.java [hunk 6]
```diff
@@ -101,24 +74,6 @@ void addOrUpdateProfileToExistingCredentialsFile() throws IOException {
...
-        credentials.addOrUpdateProfile(roleName, accessKey, secretKey, sessionToken);
-        credentials.save(credentialsWriter);
-
-        String expected = existingCredentials + "\n\n" + manualRoleCustomSuffix;
-        String given = org.apache.commons.lang.StringUtils.remove(credentialsWriter.toString().trim(), '\r');
-
-        assertEquals(expected, given);
-    }
-
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/CredentialsTest.java]: :fire: suffix customization was a workaround for the workaround causing problems for people using this with downstream tools. Removing the writes to ~/.aws/config makes testing suffix customization unnecessary.

File: src/test/java/com/okta/tools/aws/settings/CredentialsTest.java [hunk 7]
```diff
@@ -130,34 +85,7 @@ void addOrUpdateProfileToExistingProfile() throws IOException {
...
-    @Test
-    void addOrUpdateProfileToExistingProfileCustomSuffix() throws IOException {
-        final StringReader credentialsReader = new StringReader(existingCredentials + "\n\n" + manualRole);
-        final StringWriter credentialsWriter = new StringWriter();
-        final Credentials credentials = new Credentials(credentialsReader, environmentWithCustomSuffix);
-
-        final String updatedPrefix = "updated_";
-        final String expected = existingCredentials + "\n\n"
-                + manualRole + "\n\n"
-                + "[" + roleName + "_custom]\n"
```
Comment (AlainODea) [inline src/test/java/com/okta/tools/aws/settings/CredentialsTest.java]: :fire: suffix customization was a workaround for the workaround causing problems for people using this with downstream tools. Removing the writes to ~/.aws/config makes testing suffix customization unnecessary.

File: Readme.MD [hunk 8]
```diff
@@ -139,8 +138,6 @@ Here is the list of parameters that can be environment variables or settings in
   - ```OKTA_AWS_REGION``` is the default AWS region to store with the created profile.
```
Comment (davidsuehring) [inline Readme.MD]: Sounds OKTA_AWS_REGION be removed as well, or am I missing somewhere that it is used outside of the config file?

Comment (AlainODea) [reply Readme.MD]: Agreed. Done.

**Comment by AlainODea** [comment]
Thank you, @davidsuehring 😊

**Comment by davidsuehring** [comment]
@AlainODea No problem! I'm excited for the possibilities this opens up for us! Do you have any plans to cut a new release soon, or should I be looking at building the jar myself to get a version with these changes in it?

**Comment by davidsuehring** [comment]
I see that you were already ahead of me on that and built a new release this morning. Thanks!
